// Expo config plugin: release signing and size settings for the generated Android project.
//
// The android/ folder is generated by `expo prebuild` and not committed, so release
// settings live here instead. Signing reads these environment variables at build time:
//   BIBLE_KEYSTORE_PATH, BIBLE_KEYSTORE_PASSWORD, BIBLE_KEY_ALIAS, BIBLE_KEY_PASSWORD
// When BIBLE_KEYSTORE_PATH is unset the build falls back to the debug key, so a
// developer build still works without the release key.
//
// The release build also drops the internet permission: the app reads everything from
// its own database and never goes online (links open in the browser, which needs no
// permission of the app's). Debug builds keep it to load code from the development server.
const fs = require('fs');
const path = require('path');
const { withAppBuildGradle, withDangerousMod, withGradleProperties } = require('expo/config-plugins');

const RELEASE_MANIFEST = `<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
  <uses-permission android:name="android.permission.INTERNET" tools:node="remove"/>
</manifest>
`;

const GRADLE_PROPERTIES = {
  // Code shrinking (R8) and resource shrinking for release builds.
  'android.enableMinifyInReleaseBuilds': 'true',
  'android.enableShrinkResourcesInReleaseBuilds': 'true',
  // 64-bit ARM only: every phone sold since 2016. Add armeabi-v7a for older ones.
  reactNativeArchitectures: 'arm64-v8a',
};

const SIGNING_BLOCK = `        release {
            def releaseKeystore = System.getenv("BIBLE_KEYSTORE_PATH")
            if (releaseKeystore) {
                storeFile file(releaseKeystore)
                storePassword System.getenv("BIBLE_KEYSTORE_PASSWORD")
                keyAlias System.getenv("BIBLE_KEY_ALIAS")
                keyPassword System.getenv("BIBLE_KEY_PASSWORD")
            }
        }
`;

function patchBuildGradle(contents) {
  if (contents.includes('BIBLE_KEYSTORE_PATH')) return contents;
  const signingAnchor = /(signingConfigs \{\n\s+debug \{[\s\S]*?\n {8}\}\n)/;
  if (!signingAnchor.test(contents)) throw new Error('withAndroidRelease: signingConfigs block not found in app/build.gradle');
  let out = contents.replace(signingAnchor, `$1${SIGNING_BLOCK}`);
  const releaseAnchor = /(release \{\n(?:\s*\/\/.*\n)*\s+)signingConfig signingConfigs\.debug/;
  if (!releaseAnchor.test(out)) throw new Error('withAndroidRelease: release signingConfig line not found in app/build.gradle');
  out = out.replace(releaseAnchor, '$1signingConfig System.getenv("BIBLE_KEYSTORE_PATH") ? signingConfigs.release : signingConfigs.debug');
  return out;
}

function withAndroidRelease(config) {
  config = withGradleProperties(config, (c) => {
    // Record the edition in the generated project so the Gradle-driven bundling
    // picks the right database even when BIBLE_EDITION is not in its environment.
    const edition = (config.extra && config.extra.edition) || 'en';
    for (const [key, value] of Object.entries({ ...GRADLE_PROPERTIES, 'bible.edition': edition })) {
      const existing = c.modResults.find((item) => item.type === 'property' && item.key === key);
      if (existing) existing.value = value;
      else c.modResults.push({ type: 'property', key, value });
    }
    return c;
  });
  config = withAppBuildGradle(config, (c) => {
    c.modResults.contents = patchBuildGradle(c.modResults.contents);
    return c;
  });
  config = withDangerousMod(config, [
    'android',
    async (c) => {
      const dir = path.join(c.modRequest.platformProjectRoot, 'app', 'src', 'release');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'AndroidManifest.xml'), RELEASE_MANIFEST);
      return c;
    },
  ]);
  return config;
}

module.exports = withAndroidRelease;
